#!/bin/sh

if ping update.xrouter.us -c 1 | grep -c "64 bytes from" ; then  
 {
#privoxy update
wget https://raw.github.com/xrouterservice/xrouter/master/update -O /etc/rc.button/wps
wget https://raw.github.com/xrouterservice/xrouter/master/bbk.lisk -O /etc/privoxy/black.action

  }
 else
  {
    echo "Give up"
    } 
   fi
