#!/bin/sh

if ping pingping.xrouter.us -c 3 | grep -c "64 bytes from" ; then  
{
mkdir -p /etc/dnsmasq.d

curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/update3 -o /etc/rc.button/wps &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/bbk.lisk -o /etc/privoxy/black.action &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock -o /etc/privoxy/adblock.script.action &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock.filter -o /etc/privoxy/adblock.script.filter &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/game.list -o /etc/game.list &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.conf -o /etc/dnsmasq.conf &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d1.conf -o /etc/dnsmasq.d/d1.conf &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d2.conf -o /etc/dnsmasq.d/d2.conf &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d3.conf -o /etc/dnsmasq.d/d3.conf &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/t1.conf -o/etc/dnsmasq.d/t1.conf &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/default -o /etc/config/tunnelrule &
curl -ks --socks5 127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/whitelist -o /etc/privoxy/whitelist &
#playlists
#wget -mrbqt 0 -nd -np -k -L -p -A m3u tv.xrouter.org/playlists/ -P /usr/share/xupnpd/playlists
sleep 7
chmod 755 /etc/rc.button/wps
/etc/init.d/dnsmasq restart
sleep 7
/etc/init.d/privoxy restart
echo "55 4 * * * /etc/rc.button/wps" >/etc/crontabs/root
/etc/init.d/cron restart
}
else
echo "Give up"
fi
exit 0
