#!/bin/sh

if ping pingping.xrouter.us -c 3 | grep -c "64 bytes from" ; then  
{
mkdir -p /etc/dnsmasq.d
wget -e "http_proxy=http://127.0.0.1:81" -q --no-check-certificate --spider https://raw.githubusercontent.com/xrouterservice/xrouter/master/home || exit 0
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/update2 -O /etc/rc.button/wps
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/bbk.lisk -O /etc/privoxy/black.action
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock -O /etc/privoxy/adblock.script.action
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock.filter -O /etc/privoxy/adblock.script.filter
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/game.list -O /etc/game.list
#wget -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/home -O /etc/l7-protocols/dns.pat
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.conf -O /etc/dnsmasq.conf
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d1.conf -O /etc/dnsmasq.d/d1.conf
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d2.conf -O /etc/dnsmasq.d/d2.conf
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d3.conf -O /etc/dnsmasq.d/d3.conf
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/t1.conf -O /etc/dnsmasq.d/t1.conf
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/default -O /etc/config/tunnelrule
wget -e "http_proxy=http://127.0.0.1:81" -bqt 0 --no-check-certificate https://raw.githubusercontent.com/xrouterservice/xrouter/master/whitelist -O /etc/privoxy/whitelist
#playlists
#wget -mrbqt 0 -nd -np -k -L -p -A m3u tv.xrouter.org/playlists/ -P /usr/share/xupnpd/playlists
sleep 7
chmod 755 /etc/rc.button/wps
/etc/init.d/dnsmasq restart
sleep 7
/etc/init.d/privoxy restart
echo "55 4 * * * /etc/rc.button/wps" >/etc/crontabs/root
/etc/init.d/cron restart
}
else
echo "Give up"
fi
exit 0
