#Rules from Unblock-Youku by zhuzhuor et al.,
#Converted to Privoxy rules by KarlCheong
#https://github.com/karlcheong
#https://twitter.com/karlcheong

#direct=+forward-override{forward .}
#{+forward-override{forward h1.edu.bj.ie.sogou.com:80}}
#{+forward-override{forward-socks5 localhost:9050 .}}
#{+forward-override{forward h0.edu.bj.ie.sogou.com:80} +sogou-header{Reason}}

#    Addresses included in proxy.uku.im
#{+forward-override{forward localhost:8088}}    #Goagent
#{+forward-override{forward localhost:1998}}    #Sogouproxy
#{+forward-override{forward localhost:8888}}
{+forward-override{forward digito.wlmacao.tk:80}}
#interface.bilibili.tv/player.*
v.youku.com/player/.*
api.youku.com/player/.*
v2.tudou.com/.*
www.tudou.com/a/.*
www.tudou.com/v/.*
www.tudou.com/outplay/goto/getTvcCode.*
#    script filter by privoxy, proxy not needed for qqmusic
#s.plcloud.music.qq.com/fcgi-bin/p\.fcg.*
hot.vrs.sohu.com/.*
live.tv.sohu.com/live/player.*
#    script filter by privoxy, proxy not needed for letv
#hot.vrs.letv.com/.*
#g3.letv.cn/.*
#    script filter by privoxy, but not used due to loading speed
data.video.qiyi.com/.*
220.181.61.229/.*
61.135.183.45/.*
61.135.183.46/.*
220.181.19.218/.*
220.181.61.212/.*
220.181.61.213/.*
220.181.118.181/.*
123.126.48.47/.*
123.126.48.48/.*
vv.video.qq.com/getinfo.*
tt.video.qq.com/getinfo.*
ice.video.qq.com/getinfo.*
tjsa.video.qq.com/getinfo.*
a10.video.qq.com/getinfo.*
xyy.video.qq.com/getinfo.*
vcp.video.qq.com/getinfo.*
vsh.video.qq.com/getinfo.*
vbj.video.qq.com/getinfo.*
bobo.video.qq.com/getinfo.*
flvs.video.qq.com/getinfo.*
rcgi.video.qq.com/report.*
geo.js.kankan.xunlei.com/.*
web-play.pptv.com/.*
web-play.pplive.cn/.*
dyn.ugc.pps.tv/.*
v.pps.tv/ugc/ajax/aj_html5_url\.php.*
inner.kandian.com/.*
ipservice.163.com/.*
so.open.163.com/open/info\.htm.*
zb.s.qq.com/.*
ip.kankan.xunlei.com/.*
vxml.56.com/json/.*
music.sina.com.cn/yueku/intro/.*
music.sina.com.cn/radio/port/webFeatureRadioLimitList\.php.*
play.baidu.com/data/music/songlink.*
v.iask.com/v_play\.php.*
v.iask.com/v_play_ipad\.cx\.php.*
tv.weibo.com/player/.*
wtv.v.iask.com/.*\.m3u8
wtv.v.iask.com/mcdn\.php.*
www.yinyuetai.com/insite/.*
www.yinyuetai.com/main/get-.*
.dpool.sina.com.cn/iplookup.*
/vrs_flash\.action.*
/\?prot=2&type=1.*
/\?prot=2&file=/.*
#    script filter by privoxy, proxy not needed for letv
#api.letv.com/streamblock.*
api.letv.com/mms/out/video/play.*
api.letv.com/mms/out/common/geturl.*
api.letv.com/geturl.*
live.gslb.letv.com/gslb\?.*
vdn.apps.cntv.cn/api/get.*
vip.sports.cntv.cn/check\.do.*
vip.sports.cntv.cn/play\.do.*
vip.sports.cntv.cn/servlets/encryptvideopath\.do.*
api.3g.youku.com/layout.*
api.3g.youku.com/v3/play/address.*
api.3g.youku.com/openapi-wireless/videos/.*/download.*
api.3g.youku.com/videos/.*/download.*
api.3g.youku.com/common/v3/play.*
tv.api.3g.youku.com/openapi-wireless/v3/play/address.*
tv.api.3g.youku.com/common/v3/play.*
#play.api.3g.youku.com/common/v3/hasadv/play.*
play.api.3g.youku.com/common/v3/play.*
play.api.3g.youku.com/v3/play/address.*
play.api.3g.tudou.com/v.*
api.3g.tudou.com/.*
api.tv.sohu.com/mobile_user/device/clientconf\.json\?.*
access.tv.sohu.com/.*
iface2.iqiyi.com/php/xyz/iface/.*
dynamic.app.m.letv.com/.*/dynamic\.php\?.*playid.*
listso.m.areainfo.ppstream.com/ip/q\.php.*
#    script filter by privoxy, proxy not needed for letv
#api.letv.com/getipgeo
m.letv.com/api/geturl\?.*
vv.video.qq.com/getvinfo.*
bkvv.video.qq.com/getvinfo.*
3g.music.qq.com/.*
mqqplayer.3g.qq.com/.*
proxy.music.qq.com/.*
#    script filter by privoxy, proxy not needed for kugou
#ip2.kugou.com/check/isCn/.*
#ip.kugou.com/check/isCn/.*
client.api.ttpod.com/global.*
mobi.kuwo.cn/.*
#    script filter by privoxy, proxy not needed for kugou
#mobilefeedback.kugou.com/.*
tingapi.ting.baidu.com/v1/restserver/ting\?.*method=baidu\.ting\.song.*
#   script filter by privoxy, proxy not needed for duomi
#serviceinfo.sdk.duomi.com/api/serviceinfo/getserverlist.*
#   script filter by privoxy, proxy not needed for 163music
#music.163.com/api/copyright/restrict/\?.*
iplocation.geo.qiyi.com/cityjson
sns.video.qq.com/tunnel/fcgi-bin/tunnel.*
v5.pc.duomi.com/single-ajaxsingle-isban.*
openapi.youku.com/.*
61.135.196.99/.*
220.181.185.150/.*
httpbin.org/get
180.153.225.136/.*
118.244.244.124/.*
210.129.145.150/.*
182.16.230.98/.*
