#!/bin/sh

if ping ping.xrouter.us -c 1 | grep -c "64 bytes from" ; then  
 {
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/foreign/foreign/update -O /etc/rc.button/wps 2>/dev/null
wget --no-check-certificate https://github.com/karlcheong/unblock_youku_privoxy_rules/raw/master/cnfilter.action -O /etc/privoxy/black.action 2>/dev/null
wget --no-check-certificate https://github.com/karlcheong/unblock_youku_privoxy_rules/raw/master/cnforward.action -O /etc/privoxy/adblock.script.action 2>/dev/null
wget --no-check-certificate https://github.com/karlcheong/unblock_youku_privoxy_rules/raw/master/cnfilter.filter -O /etc/privoxy/adblock.script.filter 2>/dev/null
#/etc/init.d/dnsmasq restart
  }
 else
  {
    echo "Give up"
    } 
   fi
