#!/bin/sh

if ping ping.xrouter.us -c 1 | grep -c "64 bytes from" ; then  
 {
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/cmc/hd/update -O /etc/rc.button/wps -o /dev/null >/dev/null
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/bbk.lisk -O /etc/privoxy/black.action -o /dev/null >/dev/null
#wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/adblock -O /etc/privoxy/adblock.script.action -o /dev/null >/dev/null
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/home -O /etc/www.home -o /dev/null >/dev/null
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/pac -O /www/xrouter.pac -o /dev/null >/dev/null
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/cmc/hd/dnsmasq.conf -O /etc/dnsmasq.conf -o /dev/null >/dev/null
wget -b --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/default -O /etc/config/tunnelrule -o /dev/null >/dev/null
/etc/init.d/dnsmasq restart
  }
 else
  {
    echo "Give up"
    } 
   fi
