#!/bin/sh

if ping ping.xrouter.us -c 1 | grep -c "64 bytes from" ; then  
 {
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/cmc/hz/update -O /etc/rc.button/wps 2>/dev/null
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/bbk.lisk -O /etc/privoxy/black.action 2>/dev/null
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/adblock -O /etc/privoxy/adblock.script.action 2>/dev/null
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/home -O /etc/www.home 2>/dev/null
#wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/dns -O /etc/dns 2>/dev/null
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/dnsmasq.conf -O /etc/dnsmasq.conf 2>/dev/null
/etc/init.d/dnsmasq restart
  }
 else
  {
    echo "Give up"
    } 
   fi
