#!/bin/sh

if ping ping.xrouter.us -c 1 | grep -c "64 bytes from" ; then  
 {
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/tel/hb/update -O /etc/rc.button/wps
wget --no-check-certificate https://raw.github.com/xrouterservice/xrouter/master/dnsmasq.conf -O /etc/dnsmasq.conf
  }
 else
  {
    echo "Give up"
    } 
   fi
