#!/bin/sh

if ping qq.com -c 3 | grep -c "64 bytes from" ; then  
{
mkdir -p /etc/dnsmasq.d

curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/nftables/update3 -o /etc/rc.button/wps &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/bbk.lisk -o /etc/privoxy/black.action &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock -o /etc/privoxy/adblock.script.action &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/adblock.filter -o /etc/privoxy/adblock.script.filter &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/game.list -o /etc/game.list &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/regdns.conf -o /etc/dnsmasq.conf &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d1.conf -o /etc/dnsmasq.d/d1.conf &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d2.conf -o /etc/dnsmasq.d/d2.conf &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/d3.conf -o /etc/dnsmasq.d/d3.conf &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/dnsmasq.d/regnft.conf -o/etc/dnsmasq.d/t1.conf &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/default -o /etc/config/tunnelrule &
curl --retry 2 --connect-time 5 -ksx socks5h://127.0.0.1:8888 https://raw.githubusercontent.com/xrouterservice/xrouter/master/nftables/alllist -o /etc/alllist &

sleep 7
chmod 755 /etc/rc.button/wps
/etc/init.d/dnsmasq restart
sleep 7
/etc/init.d/privoxy restart
echo "55 4 * * * /etc/rc.button/wps" >/etc/crontabs/root
/etc/init.d/cron restart
}
else
echo "Give up"
fi
exit 0
